F_CPU    = 16000000UL
DEVICE   = atmega328p
BAUDRATE = 115200
PORT     = /dev/ttyUSB0
NAME     = main

BIN      = ${NAME}.bin
HEX      = ${NAME}.hex

CC       = avr-gcc
OBJCOPY  = avr-objcopy
CFLAGS   = -Os -mmcu=${DEVICE} -DF_CPU=${F_CPU}

SRCS = main.c uart.c i2c.c timer.c

OBJS = $(SRCS:.c=.o)

%.o: %.c
	${CC} ${CFLAGS} -c $< -o $@

all: flash

hex: ${HEX}

${BIN}: ${OBJS}
	${CC} ${CFLAGS} ${OBJS} -o ${BIN}

${HEX}: ${BIN}
	${OBJCOPY} -O ihex ${BIN} ${HEX}

flash: hex
	avrdude -p ${DEVICE} -c arduino -P ${PORT} -b ${BAUDRATE} -v -U flash:w:${HEX}:i

screen: flash
	screen ${PORT} ${BAUDRATE}
	
clean:
	rm -f ${BIN} ${HEX} ${OBJS}

fclean: clean

re: fclean all

.PHONY: all clean fclean re hex flash

# avr-gcc
	# -Os : -O optimise -s size// necessaire pour <utils/delay.h> plustard
	# -mmcu : compile avec le .h compatible avec notre board
	# -DF_CPU : define F_CPU (8000000UL si pas define)

#objcopy
	# -O : output intel hex voulu (format de fichier destines aux microcontrolleurs, aux eeprom)

#avrdude
	# -p : specifie le board avec lequel on travail
	# -c : utilise le programmeur donne en argument
	# -b : 115200 baud rate //"la bande passante" pour transmettre des donnees entre des appareils
	# -P : port usb du pc // ls /dev/ttyUSB*
	# -U : "flash en write le fichier hexa vers l'input de la board"

#TRUC:
#EEPROM : electrically erasable programmable read-only memory 